### PR TITLE
 #155 UI Fix for Failed Sign In

### PR DESCRIPTION
**Pull request by JBetts97**
[contributing]: https://github.com/flowhorn/schulplaner/blob/master/CONTRIBUTING.md

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: #155 

## Description

As per issue #155 it was noted that it is not obvious that the ```_FailedSignInState``` button is actually a button.
I have modified this class to use an [elevated button](https://api.flutter.dev/flutter/material/ElevatedButton/styleFrom.html) instead of an sizedbox as it allows access to the ```side``` and ```padding``` properties to improve the styling of it. This continues the continuity of the "material ui" theme. It has also been mentioned that issue #154 aims to resolve the spelling mistake, so I have not made changes to the "select methode" spelling error.

## Screenshots

**Before:**
image

**After:**
image

### CODE REVIEW

**Review by flowhorn — CHANGES_REQUESTED** [review]
Thank you for this PR. But could the look be adapted, Honestly the strong elevation is not really fitting, do you have other ideas for this design wise?

**Comment by Th3Ph4nt0m** [comment]
I think this should be splitted in 3 parts:
1. The Icon
2. The error message
3. A button

The error message should not be included in the button.

**Comment by JBetts97** [comment]
Hi @flowhorn, @Th3Ph4nt0m ,

Understood, I can see that the elevation look is not 100% fitting with the rest of the app's UI.
As @Th3Ph4nt0m mentioned we could split the icon, error message and button apart.

How about using the [card class](https://api.flutter.dev/flutter/material/Card-class.html) to make something that looks like this? Would this be more fitting?
image

**Comment by Th3Ph4nt0m** [comment]
I have just made some wireframes, what do you think about this?
</img>

**Comment by flowhorn** [comment]
Well I think a card or outline/wireframe design both would be fitting for this case :)

**Comment by JBetts97** [comment]
Nice drawing @Th3Ph4nt0m  👍,
I will make some changes to follow this new wireframe design and I will create a new pull request soon. :)

**Comment by JBetts97** [comment]
Hello @Th3Ph4nt0m , @flowhorn ,

I have just pushed some new changes.
Instead of using the elevated button, I now use a flatbutton which looks more like the rest of the UI.
I've also kept the Inkwell animation for when you click the button.

New Screenshot:
image

**Comment by Th3Ph4nt0m** [comment]
That looks way better!
I think it would be better if the button text would be "Go back" and the actual error message is displayed under the icon, don't you think?

**Comment by JBetts97** [comment]
Thanks @Th3Ph4nt0m! - Yes, I agree.
I will make another change and modify the button text to "Go Back" and I will add a message below the middle error icon.

I will make these new changes and add to the PR tomorrow evening :-)

**Comment by JBetts97** [comment]
Hello @Th3Ph4nt0m, @flowhorn ,

I've made further changes as suggested so it now contains a message next to the error icon, and I have changed the text in the button to "Go back".

Unfortunately I don't speak german, but I've used Google Translate for the following translations:
- Go Back -> Geh zurück
- Authentication Error -> Authentifizierungsfehler

Screenshot:
image

**Comment by Th3Ph4nt0m** [comment]
Thank you so much  @JBetts97 !

I have just updated one of the German translations. I recommend using this translator: https://www.deepl.com/translator

**Review by Th3Ph4nt0m — APPROVED** [review]
I have tested it and it is working. I really like it! We'll wait for Felix's review...

**Review by flowhorn — APPROVED** [review]
Looks good so far. Thank you

**Comment by JBetts97** [comment]
Thanks @Th3Ph4nt0m and @flowhorn for your positive feedback! Glad you both like it! :-)
Do I need to do anything else to merge this PR, or do we just need to wait for Felix to approve it?

**Comment by Th3Ph4nt0m** [comment]
We'll wait for Felix (aka. flowhorn) to approve these changes. There are some merge conflicts, maybe you can check and fix them, otherwise me or Felix will do that!

**Comment by JBetts97** [comment]
Thanks @Th3Ph4nt0m - Sorry I am fairly new to pull requests in GitHub.
It looks like @flowhorn has already approved this, but I am not sure how to resolve the conflicts.

**Comment by JBetts97** [comment]
Thanks @Th3Ph4nt0m - Sorry I am fairly new to pull requests in GitHub.
It looks like @flowhorn has already approved this, but I am not sure how to resolve the conflicts.

**Comment by JBetts97** [comment]
I've figured it out, and resolved the conflicts. :-)

**Comment by Th3Ph4nt0m** [comment]
I just updated the text again and compiling is working. Thank you!

**Pull request merged**
